#!/usr/bin/env python3
"""Build the Zenodo deposit archive.

Produces a single zip holding everything a reader needs to verify or rebuild
the analysis, and nothing else. Run it after a clean reproduce_all.py and a
LaTeX build, because it refuses to package outputs that are missing.

    python scripts/make_release_archive.py --version v1.0.0

What is deliberately left out, and why:

  data_raw/          213 MB of measurement data that belongs to TU Berlin. It
                     is public under CC BY 4.0 at DOI 10.14279/depositonce-25036
                     and is fetched by scripts/fetch_depositonce_dataset.py.
                     Redistributing it would fork the canonical copy and
                     detach it from its own version history. The download
                     manifest, with a SHA-256 per file, IS included.
  dft_calculations/  An abandoned DFT migration-barrier study, cut from the
                     manuscript, 79 GB of VASP output.
  .venv/, caches     Machine-local.
  manuscript/latex/_archive/
                     Working history: superseded drafts, slide decks, and
                     reading copies of third-party papers. The papers are
                     publisher PDFs that we have no right to redistribute.
                     The allow-list below cannot reach them, and .gitignore
                     keeps them out of the repository as well.
  manuscript/        Not distributed. This deposit is the analysis: code,
                     derived tables, figures and the checks that verify them.
                     The paper and its Supporting Information are the journal's
                     to publish.

Inclusion is by explicit allow-list rather than by exclusion, so a stray file
appearing in the working tree cannot leak into the deposit unnoticed.
"""

from __future__ import annotations

import argparse
import hashlib
import zipfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

# (path relative to the project root, glob or None for a single file)
INCLUDE_TREES: list[tuple[str, str]] = [
    ("scripts", "**/*.py"),
    ("src", "**/*.py"),
    ("tests", "**/*.py"),
    ("configs", "**/*"),
    ("docs", "**/*.md"),
    ("docs", "**/*.csv"),
    ("logs", "**/*.md"),
    ("notebooks", "**/*"),
    ("data_processed", "**/*.csv"),
    ("data_processed", "**/*.json"),
    ("results/tables", "**/*.csv"),
    # results/figures/ is held back until the paper is accepted. The artwork is
    # the paper's, and this deposit goes public before it does. Nothing is lost:
    # every figure is regenerated by reproduce_all.py from the released tables.
    # To ship them after acceptance, restore:
    #     ("results/figures", "**/*.png"),
    #     ("results/figures", "**/*.pdf"),
    ("results/reports", "**/*"),
    # The internal assessments record two analyses that were run and then
    # kept out of the manuscript (the Stanford multi-rate test, the low-rate
    # reconstruction). Their scripts, tables and figures are in the deposit,
    # so the notes that explain why they are absent from the paper belong
    # here too -- otherwise the deposit shows an unexplained gap.
    ("results/internal", "**/*.md"),
]

INCLUDE_FILES: list[str] = [
    "README.md",
    "LICENSE",
    "LICENSE-DATA",
    "CITATION.cff",
    ".zenodo.json",
    "requirements.txt",
    ".gitignore",
    "data_raw/download_manifest.json",
    "data_raw/README.md",
]

# Packaging a deposit that cannot be verified defeats the point.
REQUIRED = [
    "results/tables/table_delivered_energy_decomposition.csv",
    "results/tables/table_cutoff_step_budget.csv",
    "results/tables/table_final_reproducibility_check.csv",
    "scripts/reproduce_all.py",
]

# Never package these, whatever an include glob matches.
DENY_SUFFIXES = (".pyc", ".swp", ".swo", ".aux", ".log", ".spl", ".out", ".toc")
DENY_PARTS = ("__pycache__", ".ipynb_checkpoints", ".pytest_cache")


def collect() -> tuple[list[Path], list[str]]:
    seen: set[Path] = set()
    absent: list[str] = []
    for name in INCLUDE_FILES:
        path = PROJECT_ROOT / name
        if path.is_file():
            seen.add(path)
        else:
            absent.append(name)
    for tree, pattern in INCLUDE_TREES:
        base = PROJECT_ROOT / tree
        if not base.is_dir():
            continue
        for path in base.glob(pattern):
            if not path.is_file():
                continue
            if path.suffix in DENY_SUFFIXES:
                continue
            if any(part in DENY_PARTS for part in path.parts):
                continue
            seen.add(path)
    return sorted(seen), absent


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True,
                        help="release tag, e.g. v1.0.0; used in the archive name")
    parser.add_argument("--outdir", default="dist")
    args = parser.parse_args()

    missing = [name for name in REQUIRED if not (PROJECT_ROOT / name).is_file()]
    if missing:
        print("Refusing to package -- these outputs are missing. Run "
              "scripts/reproduce_all.py and build the LaTeX first:")
        for name in missing:
            print(f"  {name}")
        return 1

    files, absent = collect()
    if absent:
        print("Refusing to package -- these allow-listed files are missing "
              "(moved or renamed?):")
        for name in absent:
            print(f"  {name}")
        return 1
    outdir = PROJECT_ROOT / args.outdir
    outdir.mkdir(parents=True, exist_ok=True)
    stem = f"delivered-energy-decomposition-{args.version}"
    archive = outdir / f"{stem}.zip"

    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as zf:
        for path in files:
            zf.write(path, f"{stem}/{path.relative_to(PROJECT_ROOT)}")

    digest = hashlib.sha256(archive.read_bytes()).hexdigest()
    (outdir / f"{stem}.zip.sha256").write_text(f"{digest}  {archive.name}\n")

    size_mb = archive.stat().st_size / 1e6
    try:
        shown = archive.relative_to(PROJECT_ROOT)
    except ValueError:          # --outdir pointed outside the project
        shown = archive
    print(f"Wrote {shown}")
    print(f"  {len(files)} files, {size_mb:.1f} MB")
    print(f"  sha256 {digest}")
    print("\nUpload this zip to Zenodo. .zenodo.json carries the metadata; "
          "fill the repository URL,\nrelease tag and DOI into CITATION.cff and "
          "the manuscript's Data and Code Availability\nstatement once Zenodo "
          "issues the DOI.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
