#!/usr/bin/env python3
"""Render dist/zenodo_upload_fields.md from .zenodo.json and the built archive.

The upload sheet is what gets pasted into the Zenodo web form. It used to be
maintained by hand beside .zenodo.json and drifted from it: a stale title, a
stale SHA-256 and a check count that no longer matched the suite. Generating it
means the two cannot disagree.

    python scripts/write_zenodo_upload_fields.py --version v1.0.0
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ZENODO = ROOT / ".zenodo.json"


def render(meta: dict, archive: Path, digest: str) -> str:
    L: list[str] = []
    add = L.append
    add("# Zenodo upload form — field by field\n")
    add("Generated by `scripts/write_zenodo_upload_fields.py` from `.zenodo.json`;")
    add("edit that file, not this one. `.zenodo.json` is applied automatically only")
    add("by the GitHub–Zenodo integration, so a manual upload means filling these in")
    add("by hand.\n")
    add(f"**File to upload:** `{archive.relative_to(ROOT)}`  ")
    add(f"**SHA-256:** `{digest}`\n")
    add("---\n")
    add(f"**Resource type** — {meta['upload_type'].capitalize()}\n")
    add("**Title**\n")
    add("```\n" + meta["title"] + "\n```\n")
    add("**Creators**\n")
    for c in meta["creators"]:
        orcid = c.get("orcid") or "(none)"
        add(f"- `{c['name']}` — {c['affiliation']}  \n  ORCID: {orcid}")
    add("")
    add("**Description** — paste as HTML:\n")
    add("```html\n" + meta["description"] + "\n```\n")
    add(f"**Licence** — {meta['license'].upper()} (software); the description states "
        "CC BY 4.0 for data, figures and text.\n")
    add(f"**Access** — {meta['access_right']}   |   **Language** — {meta['language']}"
        f"   |   **Version** — {meta['version']}\n")
    add("**Keywords**\n")
    add("```\n" + ", ".join(meta["keywords"]) + "\n```\n")
    add("**Related identifiers**\n")
    for r in meta.get("related_identifiers", []):
        add(f"- `{r['identifier']}` — *{r['relation']}* — {r['resource_type']}")
    add("")
    if meta.get("grants"):
        add("**Funding**\n")
        for g in meta["grants"]:
            add(f"- `{g['id']}`")
        add("")
    if meta.get("notes"):
        add("**Notes**\n")
        add("```\n" + meta["notes"] + "\n```")
    return "\n".join(L) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", required=True, help="release tag, e.g. v1.0.0")
    ap.add_argument("--outdir", default="dist")
    args = ap.parse_args()

    meta = json.loads(ZENODO.read_text(encoding="utf-8"))
    if meta.get("version") != args.version:
        print(f"version mismatch: .zenodo.json says {meta.get('version')!r}, "
              f"--version says {args.version!r}", file=sys.stderr)
        return 1

    outdir = ROOT / args.outdir
    stem = f"undelivered-charge-vs-voltage-depression-{args.version}"
    archive, checksum = outdir / f"{stem}.zip", outdir / f"{stem}.zip.sha256"
    for path in (archive, checksum):
        if not path.is_file():
            print(f"missing {path.relative_to(ROOT)} -- run "
                  f"scripts/make_release_archive.py --version {args.version} first",
                  file=sys.stderr)
            return 1

    digest = checksum.read_text(encoding="utf-8").split()[0]
    target = outdir / "zenodo_upload_fields.md"
    target.write_text(render(meta, archive, digest), encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} (title, description and SHA-256 "
          "taken from .zenodo.json and the built archive)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
